---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr
 
     spec:
      containers:
         - name: sonarr
           image: harbor.casa.lan/multimedia/sonarr:latest
           env:
           - name: PGID
             value: "10000"
           - name: PUID
             value: "10000"
           - name: TZ
             value: "America/Sao_Paulo"
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /media
               name: movies
             - mountPath: /p2p/complete
               name: complete
             - mountPath: /etc/localtime
               name: localtime
      volumes:
        - name: sonarr-config
          hostPath:
            path: /sharedfolders/data/sonarr
        - name: movies
          hostPath:
            path: /sharedfolders/Videos
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: complete
          hostPath:
            path: /srv/dev-disk-by-id-dm-name-vg_dados-lvol1/transcode
