---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr
 
     spec:
      containers:
         - name: sonarr
           image: harbor.casa.lan/multimedia/sonarr:latest
           env:
           - name: PGID
             value: "10000"
           - name: PUID
             value: "10000"
           - name: TZ
             value: "America/Sao_Paulo"
           resources:
             limits:
               memory: "2Gi"
               cpu: "2000m"
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /media
               name: movies
             - mountPath: /p2p
               name: downloads
             - mountPath: /etc/localtime
               name: localtime
      volumes:
        - name: sonarr-config
          hostPath:
            path: /sharedfolders/configs/sonarr
        - name: movies
          hostPath:
            path: /sharedfolders/videos
        - name: downloads
          hostPath:
            path: /sharedfolders/p2p
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
