---
local_volume_provisioner_namespace: "kube-system"
local_volume_provisioner_storage_classes:
  - name: "{{ local_volume_provisioner_storage_class | default('local-storage') }}"
    host_dir: "{{ local_volume_provisioner_base_dir | default ('/mnt/disks') }}"
    mount_dir: "{{ local_volume_provisioner_mount_dir | default('/mnt/disks') }}"