---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: emby
   labels:
     app: emby
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: emby
   template:
     metadata:
       labels:
         app: emby
 
     spec:
      containers:
         - name: emby
           image: harbor.casa.lan/multimedia/emby:latest
           env:
           - name: UID
             value: "10000"
           - name: GID
             value: "10000"
           - name: GIDLIST
             value: "10000"
           volumeMounts:
             - mountPath: /config
               name: emby-config
             - mountPath: /media
               name: multimedia
      volumes:
        - name: emby-config
          hostPath:
            path: /sharedfolders/data/emby
        - name: multimedia
          hostPath:
            path: /sharedfolders/Videos/
