---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: radarr
   labels:
     app: radarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: radarr
   template:
     metadata:
       labels:
         app: radarr
 
     spec:
      containers:
         - name: radarr
           image: harbor.casa.lan/multimedia/radarr:latest
           env:
           - name: PGID
             value: "10000"
           - name: PUID
             value: "10000"
           - name: TZ
             value: "America/Sao_Paulo"
           resources:
             limits:
               memory: "2Gi"
               cpu: "500m"
           volumeMounts:
             - mountPath: /config
               name: radarr-config
             - mountPath: /media
               name: movies
             - mountPath: /p2p
               name: downloads
      volumes:
        - name: radarr-config
          hostPath:
            path: /sharedfolders/configs/radarr
        - name: movies
          hostPath:
            path: /sharedfolders/videos
        - name: downloads
          hostPath:
            path: /sharedfolders/p2p
