---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: radarr
   labels:
     app: radarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: radarr
   template:
     metadata:
       labels:
         app: radarr
 
     spec:
      containers:
         - name: radarr
           image: harbor.casa.lan/multimedia/radarr:latest
           env:
           - name: PGID
             value: "10000"
           - name: PUID
             value: "10000"
           - name: TZ
             value: "America/Sao_Paulo"
           volumeMounts:
             - mountPath: /config
               name: radarr-config
             - mountPath: /media
               name: movies
             - mountPath: /p2p/complete
               name: complete
      volumes:
        - name: radarr-config
          hostPath:
            path: /sharedfolders/data/radarr
        - name: movies
          hostPath:
            path: /sharedfolders/Videos
        - name: complete
          hostPath:
            path: /srv/dev-disk-by-id-dm-name-vg_dados-lvol1/transcode
