apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: default
provisioner: nfs1.mapfre.net # Deve ser o mesmo nome do arquivo deployment na variavel PROVISIONER_NAME - 'env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
