apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  namespace: default
provisioner: storage.casa.lan # Deve ser o mesmo nome do arquivo deployment na variavel PROVISIONER_NAME - 'env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
